services:
  alwi-db:
    image: mariadb:10.11
    container_name: alwi-db
    environment:
      - TZ=Asia/Yekaterinburg
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  alwi-php:
    build: .
    container_name: alwi-php
    environment:
      - TZ=Asia/Yekaterinburg
      - DB_PASS=${DB_PASS}
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      alwi-db:
        condition: service_healthy
    restart: unless-stopped
