services:
  alwi-db:
    image: mariadb:10.6
    container_name: alwi-db
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - alwi-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  alwi-php:
    build:
      context: .
      args:
        JENKINS_UID: "999"
        JENKINS_GID: "987"
    container_name: alwi-php
    restart: unless-stopped
    depends_on:
      alwi-db:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - alwi-net
    environment:
      - TZ=${TZ}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306

networks:
  alwi-net:
    driver: bridge
